### ISSUE TITLE
Kudo all not working (again)

### ISSUE THREAD

**Issue by jokuha** [SauceLLC/sauce4strava#166] opened 2023-08-01 07:05 UTC
As I cannot open the other issue, here's a duplicate (sorry, please close as "duplicate" once the other is re-opened)

Strava seems to have changed the layout again... at least, I do have the same problem again for some days already.

_Originally posted by @jokuha in https://github.com/SauceLLC/sauce4strava/issues/149#issuecomment-1659692334_

**Comment by MacGyverQue** [comment] 2023-08-01 16:27
Confirmed on my end as well

**Comment by iScrtAznMan** [comment] 2023-08-02 01:01
looks like #152 is open again for 8.2.3 as mentioned on #165

**Comment by elicriffield** [comment] 2023-08-03 17:19
Chrome and Brave "Kudo All" not working for me

**Comment by piaseq** [comment] 2023-08-07 10:18
Same here

**Comment by mayfield** [comment] 2023-08-07 22:06
Fixed via #167

**Closed by mayfield** 2023-08-07 22:06 UTC

**Comment by Coachbur** [comment] 2023-08-10 20:50
Any progress made on fixing Kudo All.  Seem to be getting mixed messages.

**Comment by elicriffield** [comment] 2023-08-10 21:17
It's working for me now, try uninstalling then reinstalling to make sure you have the latest version

**Comment by geno333** [comment] 2023-08-11 01:26
Yes, it resumed working again with the latest fix that came along a few days ago.

Thanks!

**Comment by Coachbur** [comment] 2023-08-11 03:09
Got it working in Chrome by turning the extension off and back on.  Uninstalled and reinstalled in Safari.  No luck.  Using Mac OS

**Comment by simonf00** [comment] 2023-08-11 15:57
Same for me... works in Chrome/Edge but does not work in Safari.

**Comment by geno333** [comment] 2023-08-11 16:04
Works fine in the Brave browser

**Comment by simonf00** [comment] 2023-08-11 16:29
Indeed... It looks like it works on Firefox and all Chromium based browsers. Safari needs fix though.

**Comment by Coachbur** [comment] 2023-08-22 00:18
Kudo all works in Chrome on Mac OS.  Does not work on anything in IOS on iPhone.
